apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: sandip525/flaskapp:9
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: myapp
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 80
  selector:
    app: myapp
